import os
from datetime import datetime, timedelta
from airflow import DAG
from lib.operators.glue import HippoGlueJobOperator
from lib.v2 import utils

# Общие параметры DAG
default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2018, 1, 31, 12, 00, 00),
    'email': ['stead@hellohippo.com'],
    'email_on_failure': False,
    'email_on_retry': False,
    'concurrency': 1,
    'retries': 1,
    'on_failure_callback': utils.send_slack_message,
    'on_retry_callback': utils.send_slack_message,
    'retry_delay': timedelta(minutes=30),
}

AWS_ACCOUNT_ID = os.getenv("AWS_ACCOUNT_ID")
AWS_REGION = os.getenv("AWS_REGION")

INVOICE_BUCKET = 'hippo-invoices-{}-{}'.format(AWS_ACCOUNT_ID, AWS_REGION)

ENV = {
    'INVOICE_BUCKET': INVOICE_BUCKET,
    'HSDK_ENV': utils.get_hippo_env(),
    'MANUAL_DATE_STRING': "{{ dag_run.conf.get('MANUAL_DATE_STRING') }}", # by default: None
    'TEST_RUN_FLAG': "{{ dag_run.conf.get('TEST_RUN_FLAG') }}", # by default: "False"
}

dag = DAG(
    'etl-invoices_cvs-yearly',
    default_args=default_args,
    schedule_interval='54 8 16 1 *',
    max_active_runs=1,
    catchup=False,
)

dag.doc_md = """
    If you want to run the task in test mode i.e. when it's too big for local run - start DAG with w/ сonfig: {"TEST_RUN_FLAG": "True"}. 
    It will ensure that the messages will be sent to the #temp-invoices Slack channel instead of #invoices and files will be saved under /temp/ prefix in S3 bucket
    If you want to run the report for specific date you need to add to the config: {'MANUAL_DATE_STRING': '2025-01-01'}.
    """
kwargs = {
    'repository_name': 'etl-invoices',
    'execution_timeout': timedelta(minutes=120),
    'worker_type': 'G.8X',
}


download_claims = HippoGlueJobOperator(
    task_id='download_claims',
    script_args={**ENV, **{'chain_name': 'cvs', 'period': 'year', 'TASK': 'download_claims'}},
    dag=dag,
    **kwargs
)
download_claims.doc_md = """
# Download claims for CVS yearly report. Saves resulting dataframe as .parquet file

"""

download_sources = HippoGlueJobOperator(
    task_id='download_sources',
    script_args={**ENV, **{'chain_name': 'cvs', 'period': 'year', 'TASK': 'download_sources'}},
    dag=dag,
    **kwargs
)
download_sources.doc_md = """
# Download shource files for CVS yearly report. Saves resulting dataframe as .parquet file
"""

cvs_yearly = HippoGlueJobOperator(
    task_id='cvs_yearly',
    script_args={**ENV, **{'chain_name': 'cvs', 'period': 'year', 'TASK': 'cvs_yearly'}},
    dag=dag,
    **kwargs
)
cvs_yearly.doc_md = """
#Generate yearly reconciliation for all CVS programs. Post to slack in #invoices

"""

wipe_temp_data_in_s3 = HippoGlueJobOperator(
    task_id=f'wipe_temp_data_in_s3_all_data',
    script_args={**ENV, **{'chain_name': 'cvs', 'period': 'year', 'TASK': 'wipe_temp_data_in_s3'}},
    dag=dag,
    **kwargs
)

wipe_temp_data_in_s3.doc_md = """\
# Delete all temporal data in s3://hippo-invoices-... generated by download_claims and download_sources.
Delete only data for specific chain and period 
"""

download_claims >> download_sources >> cvs_yearly >> wipe_temp_data_in_s3
